### ISSUE TITLE
Numeric equivalence with MATLAB PREP

### ISSUE THREAD

**Issue by a-hurst** [sappelhoff/pyprep#58]
This is a general tracking issue for the numeric equivalence of PyPREP vs Matlab PREP at each stage of the pipeline. I figure this will be useful for keeping a bird's eye view of what's been tested and what hasn't, as well as what parts have been confirmed to differ.

Guide: items with a checkmark have been tested and confirmed as producing identical results to MATLAB. Items with no checkmark and a corresponding issue # have been tested and confirmed as diverging. Items with no checkmark and no issue number have yet to be formally tested.

### NoisyChannels Methods

 - [x] Bad by NaN
 - [x] Bad by flat (fixed by #60)
 - [x] Bad by deviation (fixed by #57)
 - [x] Bad by HF noise
 - [x] Bad by correlation (fixed by #57)
 - [x] Bad by low SNR (fixed by #57)
 - [x] Bad by dropout (fixed by #81)
 - [x] Bad by RANSAC
      - [x] 'Bad' channel exclusion (fixed by #64)
      - [x] Channel picks (with fixed seed) (fixed by #62)
      - [x] Spherical interpolation algorithm (with identical channel locations, produces identical matrix 🎉)
      - [x] Channel interpolation (fixed by #70)
      - [x] Channel correlation (fixed by #67 and #70)
      - [x] Channel thresholding

### Other Functions

- [x] removeTrend (fixed by #71)
- [ ] CleanLine (`mne.filter.notch_filter`) (#82: PyPREP's line noise removal is different, seems to be more aggressive)
- [x] Robust re-referencing
     - [x] Initial average referencing (fixed by #78)
     - [x] Reference removal
     - [x] Bad channel identification (fixed by #78, #89, and #93)
     - [x] Bad channel interpolation (fixed by #96)
     - [x] Final re-referencing (fixed by #92)
- [x] Final bad channel interpolation (fixed by #92 and #96)

**Comment by sappelhoff** [comment]
Hey @a-hurst this is amazing, you are doing a lot of great work for pyprep, thanks :-) I sent you a "collaborator" invitation for this GitHub repo, which will give you a couple of more permissions that will hopefully be helpful for organizing labels, milestones, reviews, etc.

**Comment by a-hurst** [comment]
@sappelhoff Glad I can help! I've definitely learned a lot through the process so far. Thanks for the collaborator invite, and for your helpful feedback on my posts and PRs!

**Comment by a-hurst** [comment]
@sappelhoff @yjmantilla do either of you have any data with channel drop-outs, just so I can test that and (hopefully) check it off? Or would that be really easy to simulate for a given recording? As an EEG novice (my background is almost entirely behavioural psych), I'm assuming that dropouts are what happens when the amplifier loses connection with an electrode for some reason, but I'm not sure how that ends up looking in the data.

**Comment by sappelhoff** [comment]
> do either of you have any data with channel drop-outs, just so I can test that and (hopefully) check it off?

Mh I don't have such data at hand right now (nothing comes to mind), but for the data that I worked with (BrainVision ".vhdr+.vmrk+.eeg" [format](https://github.com/bids-standard/pybv)), I never encountered NaN values during recording or analysis.

I did have some recordings where an electrode got loose and then connection was bad ... and other cases where an electrode itself was broken.

That usually resulted in very flat (very low variance and amplitude) signals.

**Comment by a-hurst** [comment]
> but for the data that I worked with (BrainVision ".vhdr+.vmrk+.eeg" format), I never encountered NaN values during recording or analysis.

I don't think EDF/BDF files have any concept of NaN either, since all data is stored exclusively as integers. Maybe EEGLAB generates NaNs under certain circumstances that MNE doesn't? If that's the case, maybe for PyPREP dropouts should be based on windows where the signal is totally flat instead of windows where the signal is NaN. The original PREP publication reports a dataset they used where they had considerable dropouts, so maybe I should fire them an email...

**Comment by sappelhoff** [comment]
Once numerical equivalence with matlab PREP is reached, we can consider removing the "ALPHA SOFTWARE" warning from the README:

> ALPHA SOFTWARE. This package is currently in its early stages of iteration. It may change both its internals or its user-facing API in the near future. Any feedback and ideas on how to improve either of these is more than welcome! Use this software at your own risk.

**Comment by yjmantilla** [comment]
Seems I unpinned this issue without me noticing (maybe I miss-clicked somewhere (?)). Pinning it back.

**Comment by a-hurst** [comment]
@sappelhoff @yjmantilla With the merging of #96, I think we've identified and resolved every deviation between PyPREP and MatPREP apart from the adaptive line noise stuff 🎉🎊🎉. Massive thanks to you both for your help, feedback, and support in my crusade against issue #41 and beyond: I feel like I've grown a lot as a programmer from the collaborative atmosphere and the detailed code review I've received contributing to this project.

Anyway, since the CleanLine stuff has been bumped to 0.5.0, should this issue get bumped to 0.5.0 as well, or should it be closed in favour of #82 since it's the only component remaining?

**Comment by sappelhoff** [comment]
🎉 🚀 awesome! :-) You are doing a tremendous job and it's a pleasure to review your PRs - always cleanly documented, well described, and effective. I am happy you've taken something beyond the (already awesome) improvement of PyPrep (I also did / and do in my role as maintainer/reviewer).

I think this issue can be closed with its last box (cleanline) unticked until we close #82. I'll leave the closing and unpinning of this one (#58) to you :-) cheers!

PS: Can't wait to finally ship all the good stuff in 0.4

**Comment by yjmantilla** [comment]
Also very happy! I haven't really contributed to pyprep these last months but I feel like-wise as @a-hurst said:
> I feel like I've grown a lot as a programmer from the collaborative atmosphere and the detailed code review I've received contributing to this project.

So a lot of thanks to @sappelhoff for the patience and reviews too.

**Comment by a-hurst** [comment]
Thanks! 🙂 And yeah, a lot of my open-source experience has been contributing to semi-abandoned projects that I've tried to keep alive (specifically eyelinker and pysdl2), so outside of PyPREP I haven't had many opportunities to do real collaborative software work. It's been a nice change of pace! A lot easier to stay motivated to see something like this through when you know at *least* one or two other people are going to notice and appreciate it 😊

Anyway, closing this via #96!

**Comment by sappelhoff** [comment]
Thanks @yjmantilla I am glad the reviews helped you :)
